import PDFDocument from "pdfkit";

type BrandForPdf = {
  name: string;
  tagline?: string | null;
  description?: string | null;
  primaryColor?: string | null;
  secondaryColors?: string | null;
  headingFont?: string | null;
  bodyFont?: string | null;
  toneOfVoice?: string | null;
  personalityTraits?: string | null;
  targetAudience?: string | null;
  visualStyle?: string | null;
  image?: string | null;
  deepAnalysis?: string | null;
};

type PdfOptions = {
  includeAssets?: boolean;
  assets?: Array<{ label: string; type: string; url?: string | null }>;
};

function safeJsonArray(value: string | null | undefined): string[] {
  if (!value) return [];
  try {
    const parsed = JSON.parse(value) as unknown;
    return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === "string") : [];
  } catch {
    return [];
  }
}

function toCmykHexLabel(hex: string): string {
  const normalized = hex.startsWith("#") ? hex : `#${hex}`;
  return `${normalized.toUpperCase()} / CMYK approx`;
}

function writeSectionTitle(doc: PDFKit.PDFDocument, title: string): void {
  doc.moveDown(0.6);
  doc.fontSize(14).fillColor("#111111").text(title);
  doc.moveTo(50, doc.y + 2).lineTo(545, doc.y + 2).strokeColor("#E5E7EB").stroke();
  doc.moveDown(0.8);
}

function addCover(doc: PDFKit.PDFDocument, brand: BrandForPdf): void {
  doc.rect(0, 0, 595, 180).fill(brand.primaryColor || "#EA751D");
  doc.fillColor("#FFFFFF");
  doc.fontSize(12).text("Brand Kit", 50, 50);
  doc.fontSize(32).text(brand.name || "Brand", 50, 80, { width: 500 });
  if (brand.tagline) {
    doc.fontSize(14).fillColor("#F3F4F6").text(brand.tagline, 50, 128, { width: 500 });
  }
  doc.fillColor("#111111");
  doc.y = 220;
}

export async function generateBrandKitPDF(
  brand: BrandForPdf,
  options: PdfOptions = {}
): Promise<Buffer> {
  const doc = new PDFDocument({ size: "A4", margin: 50 });
  const chunks: Buffer[] = [];
  doc.on("data", (chunk) => chunks.push(Buffer.from(chunk)));

  addCover(doc, brand);

  const secondaryColors = safeJsonArray(brand.secondaryColors);
  const traits = safeJsonArray(brand.personalityTraits);
  const allColors = [brand.primaryColor || "#EA751D", ...secondaryColors].filter(Boolean).slice(0, 6);

  writeSectionTitle(doc, "Brand Strategy");
  doc.fontSize(11).fillColor("#374151").text(`Vision: ${brand.description || "Not provided"}`);
  doc.moveDown(0.4);
  doc.text(`Tone of voice: ${brand.toneOfVoice || "Not provided"}`);
  doc.moveDown(0.4);
  doc.text(`Target audience: ${brand.targetAudience || "Not provided"}`);
  doc.moveDown(0.4);
  doc.text(`Personality: ${traits.join(", ") || "Not provided"}`);

  writeSectionTitle(doc, "Color Guidelines");
  const startY = doc.y;
  allColors.forEach((color, index) => {
    const x = 50 + index * 80;
    doc.rect(x, startY, 52, 52).fill(color).strokeColor("#D1D5DB").stroke();
    doc.fillColor("#111827").fontSize(8).text(toCmykHexLabel(color), x, startY + 58, { width: 70 });
  });
  doc.y = startY + 90;

  writeSectionTitle(doc, "Typography");
  doc.fontSize(11).fillColor("#374151").text(`Heading font: ${brand.headingFont || "System UI"}`);
  doc.moveDown(0.3);
  doc.text(`Body font: ${brand.bodyFont || "System UI"}`);
  doc.moveDown(0.3);
  doc.text(`Application: Keep consistent hierarchy and spacing across digital and print.`);

  writeSectionTitle(doc, "Identity Guidelines");
  doc.fontSize(11).fillColor("#374151").text("Logo clear space: Use at least 1x logo-height around the mark.");
  doc.moveDown(0.3);
  doc.text("Logo do: Preserve proportions and high contrast.");
  doc.moveDown(0.3);
  doc.text("Logo don't: Stretch, rotate, add effects, or recolor arbitrarily.");

  if (options.includeAssets && options.assets && options.assets.length > 0) {
    writeSectionTitle(doc, "Sample Assets");
    options.assets.slice(0, 8).forEach((asset, idx) => {
      doc.fontSize(10).fillColor("#111827").text(`${idx + 1}. ${asset.label} (${asset.type})`);
      if (asset.url) {
        doc.fontSize(8).fillColor("#6B7280").text(asset.url);
      }
      doc.moveDown(0.2);
    });
  }

  doc.moveDown(1);
  doc.fontSize(9).fillColor("#9CA3AF").text(`Generated by BrandBloom on ${new Date().toLocaleDateString()}`);
  doc.end();

  await new Promise<void>((resolve) => {
    doc.on("end", () => resolve());
  });
  return Buffer.concat(chunks);
}
