import Link from "next/link";

export default function TermsPage() {
  const sections = [
    { title: "1. Acceptance of Terms", body: "By using BrandBloom you agree to these Terms. If you don't agree, please don't use the service." },
    { title: "2. Description of Service", body: "BrandBloom is an AI-powered brand asset generation platform. We extract brand identity from URLs and logos, and generate visual assets using AI image generation models." },
    { title: "3. Account Registration", body: "You must be 18 or older to use BrandBloom. You're responsible for keeping your account credentials secure and for all activity under your account." },
    { title: "4. Credits & Payments", body: "Credits are purchased through Stripe. One-time credit purchases are non-refundable once credits have been used. Unused credits from one-time purchases never expire. Monthly subscription credits reset on your billing date. We reserve the right to change pricing with 30 days notice." },
    { title: "5. Acceptable Use", body: "You may not use BrandBloom to generate content that is illegal, harmful, deceptive, or violates third-party intellectual property rights. We reserve the right to suspend accounts that violate these terms." },
    { title: "6. Intellectual Property", body: "You retain full ownership of brand assets you generate using BrandBloom. You grant us a limited license to process your inputs (URLs, logos, images) solely to provide the service." },
    { title: "7. AI-Generated Content", body: "Assets are generated by AI and may occasionally produce unexpected results. You are responsible for reviewing generated content before use. BrandBloom makes no warranty that generated assets are free from intellectual property claims." },
    { title: "8. Disclaimer of Warranties", body: "BrandBloom is provided 'as is' without warranty of any kind. We don't guarantee the service will be error-free, uninterrupted, or that outputs will meet your specific requirements." },
    { title: "9. Limitation of Liability", body: "To the maximum extent permitted by law, BrandBloom's total liability for any claims is limited to the amount you paid in the 12 months preceding the claim." },
    { title: "10. Termination", body: "We may suspend or terminate your account for violation of these Terms. You may close your account at any time from Settings. On termination, your data is deleted within 30 days." },
    { title: "11. Changes to Terms", body: "We may update these Terms. We'll notify you by email or in-app for material changes. Continued use after changes constitutes acceptance." },
    { title: "12. Contact", body: "For questions about these Terms, email us at legal@brandbloom.ai." },
  ];

  return (
    <div className="min-h-screen bg-surface-900 text-white">
      <nav className="fixed inset-x-0 top-0 z-50 border-b border-white/[0.05] bg-surface-900/80 backdrop-blur-md">
        <div className="mx-auto flex h-16 max-w-4xl items-center justify-between px-4">
          <Link href="/" className="flex items-center gap-2">
            <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-brand-500 text-xs font-bold">B</div>
            <span className="text-sm font-bold">BrandBloom</span>
          </Link>
          <Link href="/" className="text-sm text-stone-400 hover:text-white transition-colors">← Home</Link>
        </div>
      </nav>
      <div className="mx-auto max-w-2xl px-4 pb-24 pt-28">
        <div className="mb-10">
          <h1 className="text-3xl font-bold text-white">Terms of Service</h1>
          <p className="mt-2 text-sm text-stone-500">Last updated: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</p>
        </div>
        <div className="space-y-8">
          {sections.map((s) => (
            <div key={s.title}>
              <h2 className="mb-2 text-base font-bold text-white">{s.title}</h2>
              <p className="text-sm leading-relaxed text-stone-400">{s.body}</p>
            </div>
          ))}
        </div>
        <div className="mt-12 border-t border-surface-600 pt-8 text-sm text-stone-600">
          <Link href="/privacy" className="text-brand-400 hover:text-brand-300 underline underline-offset-2">Privacy Policy</Link>
          {" · "}
          <Link href="/" className="hover:text-stone-400 transition-colors">Home</Link>
        </div>
      </div>
    </div>
  );
}